### PR TITLE
Do not parse docker version when validation is disabled

### LINKED ISSUE #1502: Error while determining supported Docker version for dev
**RKE version:**
0.2.6
**Docker version: (`docker version`,`docker info` preferred)**
```
Client:
 Version:           18.06.3
 API version:       1.38
 Go version:        go1.12
 Git commit:        d7080c1
 Built:             Thu Mar 28 16:22:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.12
  Git commit:       d7080c1
  Built:            Thu Mar 28 16:21:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME=Fedora
VERSION="30-cs.20190725.prod.1 (CoreOS preview)"
ID=fedora
VERSION_ID=30
VERSION_CODENAME=""
PLATFORM_ID="platform:f30"
PRETTY_NAME="Fedora 30-cs.20190725.prod.1 (CoreOS preview)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:30"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f30/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=30
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=30
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS preview"
VARIANT_ID=coreos
OSTREE_VERSION=30-cs.20190725.prod.1

5.1.18-301.fc30.x86_64
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
bare-metal
**cluster.yml file:**
not important
**Steps to Reproduce:**
Install fedora coreos preview, add core user to docker group and try to setup rke
**Results:**
fedora coreos is shipped with `moby-engine` (https://pkgs.org/download/moby-engine)
this engine is displaying version as "dev"
in this case rke is failing to parse version number and removing host from list
`ignore-docker-version` option isn't working in this case, because check is made after version is parded

### PR DESCRIPTION
**Pull request by Szpadel**
When IgnoreDockerVersion is set, do not try to parse its version number
Still retrieve docker info to check check fi docker is reachable

https://github.com/rancher/rke/issues/1502

### CODE REVIEW

File: hosts/tunnel.go [hunk 1]
```diff
@@ -65,6 +65,9 @@ func checkDockerVersion(ctx context.Context, h *Host, clusterVersion string) err
 		return fmt.Errorf("Can't retrieve Docker Info: %v", err)
 	}
 	logrus.Debugf("Docker Info found: %#v", info)
+	if h.IgnoreDockerVersion {
```
Comment (leodotcloud) [inline hosts/tunnel.go]: docker info is not populated if this block returns here. Needs to be moved below.

File: hosts/tunnel.go [hunk 2]
```diff
@@ -76,7 +79,7 @@ func checkDockerVersion(ctx context.Context, h *Host, clusterVersion string) err
 		return fmt.Errorf("Error while determining supported Docker version [%s]: %v", info.ServerVersion, err)
 	}
 
-	if !isvalid && !h.IgnoreDockerVersion {
+	if !isvalid {
```
Comment (leodotcloud) [inline hosts/tunnel.go]: Need to revisit the entire if/else block. There is probably going to be only one if block when `&& !h.IgnoreDockerVersion` is removed.
